### ISSUE TITLE
ValueError: Input data has zero size. Please provide non-empty data

### ISSUE THREAD

**Issue by sadmanomee** [usnistgov/alignn#122]
Engine run is terminating due to exception: Input data has zero size. Please provide non-empty data                                           
Traceback (most recent call last):
  File "/work/somee/MD_HIT_structure/alignn/alignn/train_folder.py", line 214, in <module>
    train_for_folder(
  File "/work/somee/MD_HIT_structure/alignn/alignn/train_folder.py", line 197, in train_for_folder
    train_dgl(
  File "/work/somee/alignn/alignn/train.py", line 961, in train_dgl
    trainer.run(train_loader, max_epochs=config.epochs)
  File "/work/somee/alignn_env/lib/python3.10/site-packages/ignite/engine/engine.py", line 900, in run
    return self._internal_run()
  File "/work/somee/alignn_env/lib/python3.10/site-packages/ignite/engine/engine.py", line 943, in _internal_run
    return next(self._internal_run_generator)
  File "/work/somee/alignn_env/lib/python3.10/site-packages/ignite/engine/engine.py", line 1001, in _internal_run_as_gen
    self._handle_exception(e)
  File "/work/somee/alignn_env/lib/python3.10/site-packages/ignite/engine/engine.py", line 639, in _handle_exception
    raise e
  File "/work/somee/alignn_env/lib/python3.10/site-packages/ignite/engine/engine.py", line 973, in _internal_run_as_gen
    self._fire_event(Events.EPOCH_COMPLETED)
  File "/work/somee/alignn_env/lib/python3.10/site-packages/ignite/engine/engine.py", line 426, in _fire_event
    func(*first, *(event_args + others), **kwargs)
  File "/work/somee/alignn/alignn/train.py", line 881, in log_results
    evaluator.run(val_loader)
  File "/work/somee/alignn_env/lib/python3.10/site-packages/ignite/engine/engine.py", line 861, in run
    raise ValueError("Input data has zero size. Please provide non-empty data")
ValueError: Input data has zero size. Please provide non-empty data

**Comment by meiirbek-islamov** [comment]
I believe you need to increase the size of your dataset to have more data points in your validation dataset.

**Comment by sadmanomee** [comment]
Thank you, I was making test run on a small dataset.
