### ISSUE TITLE
AttributeError: module 'profile' has no attribute 'run'

### ISSUE THREAD

**Issue by xiaowangfeng** [usnistgov/alignn#158]
Hello,pro , I use the 
git clone https://github.com/usnistgov/alignn
cd alignn
python -m pip install -e . 
to install the alignn 

but when i run train_alignn.py --root_dir "alignn/examples/sample_data" --config "alignn/examples/sample_data/config_example.json" --output_dir=tem , it will happened 
Traceback (most recent call last):
  File "/data/run01/scv7f2x/software-scv7f2x/alignn/alignn/train_alignn.py", line 446, in <module>
    train_for_folder(
  File "/data/run01/scv7f2x/software-scv7f2x/alignn/alignn/train_alignn.py", line 402, in train_for_folder
    train_dgl(
  File "/data/run01/scv7f2x/software-scv7f2x/alignn/alignn/train.py", line 242, in train_dgl
    optimizer = setup_optimizer(params, config)
  File "/data/run01/scv7f2x/software-scv7f2x/alignn/alignn/train.py", line 94, in setup_optimizer
    optimizer = torch.optim.AdamW(
  File "/data/home/scv7f2x/.conda/envs/my_alignn/lib/python3.10/site-packages/torch/optim/adamw.py", line 53, in __init__
    super().__init__(params, defaults)
  File "/data/home/scv7f2x/.conda/envs/my_alignn/lib/python3.10/site-packages/torch/optim/optimizer.py", line 284, in __init__
    self.add_param_group(cast(dict, param_group))
  File "/data/home/scv7f2x/.conda/envs/my_alignn/lib/python3.10/site-packages/torch/_compile.py", line 22, in inner
    import torch._dynamo
  File "/data/home/scv7f2x/.conda/envs/my_alignn/lib/python3.10/site-packages/torch/_dynamo/__init__.py", line 2, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "/data/home/scv7f2x/.conda/envs/my_alignn/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 40, in <module>
    from . import config, exc, trace_rules
  File "/data/home/scv7f2x/.conda/envs/my_alignn/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 11, in <module>
    from .utils import counters
  File "/data/home/scv7f2x/.conda/envs/my_alignn/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 5, in <module>
    import cProfile
  File "/data/home/scv7f2x/.conda/envs/my_alignn/lib/python3.10/cProfile.py", line 23, in <module>
    run.__doc__ = _pyprofile.run.__doc__
AttributeError: module 'profile' has no attribute 'run'

can you tell me how to solve it?

thanks very much  

this is my packbag

alignn             2024.4.20   /data/run01/scv7f2x/software-scv7f2x/alignn
annotated-types    0.7.0
ase                3.23.0
Brotli             1.0.9
certifi            2024.6.2
charset-normalizer 2.0.4
contourpy          1.2.1
cycler             0.12.1
dgl                1.0.2+cu118
filelock           3.13.1
flake8             7.1.0
fonttools          4.53.0
fsspec             2024.6.1
gmpy2              2.1.2
idna               3.7
inflect            7.3.0
jarvis-tools       2024.5.10
Jinja2             3.1.4
joblib             1.4.2
kiwisolver         1.4.5
lmdb               1.4.1
MarkupSafe         2.1.3
matplotlib         3.9.0
mccabe             0.7.0
mkl-fft            1.3.8
mkl-random         1.2.4
mkl-service        2.4.0
more-itertools     10.3.0
mpmath             1.3.0
networkx           3.2.1
numpy              1.26.4
packaging          23.2
pandas             2.2.2
pillow             10.3.0
pip                24.0
platformdirs       3.10.0
pooch              1.7.0
psutil             5.9.0
pycodestyle        2.12.0
pydantic           2.7.4
pydantic_core      2.18.4
pydantic-settings  2.3.4
pydocstyle         6.3.0
pyflakes           3.2.0
pyparsing          2.4.7
PySocks            1.7.1
python-dateutil    2.9.0.post0
python-dotenv      1.0.1
pytz               2024.1
PyYAML             6.0.1
requests           2.32.2
scikit-learn       1.5.0
scipy              1.10.1
setuptools         69.5.1
six                1.16.0
snowballstemmer    2.2.0
spglib             2.4.0
sympy              1.12
threadpoolctl      3.5.0
toolz              0.12.1
torch              2.3.1
torchaudio         2.3.1
torchvision        0.18.1
tqdm               4.66.4
triton             2.3.1
typeguard          4.3.0
typing_extensions  4.11.0
tzdata             2024.1
urllib3            2.2.2
wheel              0.43.0
xmltodict          0.13.0

python--3.10.14

**Comment by bdecost** [comment]
looks like this is a name collision between alignn/profile.py and the built-in profile module - see https://stackoverflow.com/a/57325589

This PR should address that - https://github.com/usnistgov/alignn/pull/159

**Comment by xiaowangfeng** [comment]
thanks for your answer, but when i modify profile to profiler like- https://github.com/usnistgov/alignn/pull/159- https://github.com/usnistgov/alignn/pull/159 , it will have the new question 
Traceback (most recent call last):
  File "/data/run01/scv7f2x/software-scv7f2x/alignn/alignn/train_alignn.py", line 446, in <module>
    train_for_folder(
  File "/data/run01/scv7f2x/software-scv7f2x/alignn/alignn/train_alignn.py", line 402, in train_for_folder
    train_dgl(
  File "/data/run01/scv7f2x/software-scv7f2x/alignn/alignn/train.py", line 566, in train_dgl
    mean_out, mean_atom, mean_grad, mean_stress = get_batch_errors(
  File "/data/run01/scv7f2x/software-scv7f2x/alignn/alignn/train.py", line 313, in get_batch_errors
    if "target_out" in i:
UnboundLocalError: local variable 'i' referenced before assignment

I don't modify the code ,so i don't know what happened

thanks

**Comment by bdecost** [comment]
that looks like a separate issue, it looks like the function [get_batch_errors](https://github.com/usnistgov/alignn/blob/develop/alignn/train.py#L268)is being called with no arguments, so [this loop](https://github.com/usnistgov/alignn/blob/develop/alignn/train.py#L281) doesn't run any iterates and then triggers the error you report [at line 313](https://github.com/usnistgov/alignn/blob/develop/alignn/train.py#L313) where `i` is not defined

@knc6 wrote this particular function so I'm not totally sure where to start in terms of how this function is called and what the inputs are expected to be... This is in a code path that's specific to the `alignn_atomwise` model, so maybe you could check your model/training configuration to make sure everything makes sense?

**Comment by xiaowangfeng** [comment]
thanks, i will try it .

**Comment by knc6** [comment]
@xiaowangfeng I was not able to reproduce your error:

https://github.com/knc6/jarvis-tools-notebooks/blob/master/jarvis-tools-notebooks/ALIGNN_Installation_GH_issue.ipynb

Are you still working with the sample dataset or a new dataset?

**Comment by xiaowangfeng** [comment]
of course, I use the  sample dataset.  I also want to know what happened.       

In the front , I introduce the  packbag

**Comment by xiaowangfeng** [comment]
@knc6 

thanks again
