### ISSUE TITLE
CIF File non-iterable NoneType object Error

### ISSUE THREAD

**Issue by MiracAydin1** [usnistgov/alignn#79]
Dear All,

I train ALIGNN with cif files. To improve the performance, I tried to augment my cif files with AugLiChem library. Here is the snippet from the original file and the augmented cif file:

Original file:

```
data_image0
_chemical_formula_structural       H10C14S2N2O2
_chemical_formula_sum              "H10 C14 S2 N2 O2"
_cell_length_a       4.3258
_cell_length_b       8.982
_cell_length_c       8.4721
_cell_angle_alpha    90
_cell_angle_beta     90.594
_cell_angle_gamma    90

_space_group_name_H-M_alt    "P 1"
_space_group_IT_number       1

loop_
  _space_group_symop_operation_xyz
  'x, y, z'

loop_
  _atom_site_type_symbol
  _atom_site_label
  _atom_site_symmetry_multiplicity
  _atom_site_fract_x
  _atom_site_fract_y
  _atom_site_fract_z
  _atom_site_occupancy
  H   H1        1.0  0.83700  0.83300  0.55800  1.0000
  H   H2        1.0  0.16300  0.33300  0.44200  1.0000
.
.
.
(continues)
```

Augmented file:

```
# generated using pymatgen
data_H5C7SNO
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   4.32580000
_cell_length_b   8.98200000
_cell_length_c   8.47210000
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.59400000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   H5C7SNO
_chemical_formula_sum   'H10 C14 S2 N2 O2'
_cell_volume   329.16012678
_cell_formula_units_Z   2
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  H  H0  1  0.83420779  0.82961480  0.54722879  1.0
  H  H1  1  0.15729856  0.32521300  0.43626670  1.0
.
.
.
(continues)

```

ALIGNN works fine with original cif files but whenever I try to train it with augmented file, I encounter the following error:

```
Using backend: pytorch
Traceback (most recent call last):
  File "/raid/apps/alignn/2021/bin/train_folder.py", line 195, in <module>
    train_for_folder(
  File "/raid/apps/alignn/2021/bin/train_folder.py", line 103, in train_for_folder
    atoms = Atoms.from_cif(file_path)
  File "/raid/apps/alignn/2021/lib/python3.8/site-packages/jarvis/core/atoms.py", line 537, in from_cif
    cif_atoms = cif_atoms.get_primitive_atoms
  File "/raid/apps/alignn/2021/lib/python3.8/site-packages/jarvis/core/atoms.py", line 710, in get_primitive_atoms
    return Spacegroup3D(self).primitive_atoms
  File "/raid/apps/alignn/2021/lib/python3.8/site-packages/jarvis/analysis/structure/spacegroup.py", line 240, in primitive_atoms
    lattice, scaled_positions, numbers = spglib.find_primitive(
TypeError: cannot unpack non-iterable NoneType object
```

I can not see a problem in augmented files. Do you have any suggestions?

Best regards,

**Comment by bdecost** [comment]
Hi @MiracAydin1, can you please attach the full CIF file and share the versions you're using for at least jarvis-tools and spglib?

This looks like a potential issue with https://github.com/usnistgov/jarvis. Have you tried any other CIF parsers?

**Comment by bdecost** [comment]
a possible workaround might be to parse the structures using pymatgen and convert to jarvis Atoms, since your augmented file seems to have been written by the pymatgen CIF io module

**Comment by knc6** [comment]
Can you try to install cif2cell `pip install cif2cell==2.0.0a3` ? jarvis-tools by default will use it and hopefully the issue should be resolved https://github.com/usnistgov/jarvis/blob/master/jarvis/core/atoms.py#L304  .
Also as @bdecost mentioned please feel free to send the cif file via email or attach here.

**Comment by MiracAydin1** [comment]
Hi @knc6, I installed the package.

Then I checked "config.json" file. Giving the exact number of the length of dataset gives error. I reduced the number of "n_val", "n_test" and "n_train" values

```
{
        "version": "1859f483ea2b41f6163b845eb689f0f1afdd1e8f",
        "dataset": "user_data",
        "target": "target",
        "atom_features": "cgcnn",
        "neighbor_strategy": "k-nearest",
        "random_seed": 123,
        "classification_threshold": null,
        "n_val": 5350,
        "n_test": 5350,
        "n_train": 42000,
        "train_ratio": 0.8,
        "val_ratio": 0.1,
        "test_ratio": 0.1,
        "target_multiplication_factor": null,
        "epochs": 300,
```
After reducing the values by around 10 molecules. The model started to work. I think these numbers are not automatically detected by the length of dataset. Assigning these values manually can cause error sometimes if you give a value more then the length of dataset.
